### ISSUE TITLE
Error running in Psychopy

### ISSUE THREAD

**Issue by nicballarin** [ianhussey/IAT#6]
When I try to run the program in PsychoPy, I get to the instruction page and as soon as I press E or I, it crashes and gives me the following error:

Traceback (most recent call last):
  File "/Users/Nic/Desktop/Thesis/IAT Downloads/ImplicitAssociationTest-master/IAT.py", line 572, in <module>
    if not isinstance('requiredAllowed', basestring):
NameError: name 'basestring' is not defined

**Comment by ianhussey** [comment]
I googled your name error and found [this](https://stackoverflow.com/questions/34803467/unexpected-exception-name-basestring-is-not-defined-when-invoking-ansible2), which suggests that you might be trying to run the script in the Python 3 version of PsychoPy rather than the Python 2 version. This Python 3 version was added recently. I'll add a note to the readme that you need to run it in the Python 2 version.
